spring:
  main:
    banner-mode: "off"

keybout:
  latency: 0
  min-word-length: 5
  max-word-length: 12

logging.level:
  ROOT: INFO

---

spring.profiles: color

spring.output.ansi.enabled: ALWAYS

---

spring.profiles: dev

logging.level:
  com.adeliosys: TRACE
